namespace LocalUtilities.IocpNet.Common;

public enum ProtocolCode
{
    None,
    Success,
    UnknowError,
    PacketLengthError,
    PacketFormatError,
    UnknownCommand,
    CommandNoCompleted,
    ParameterError,
    ParameterInvalid,
    UserOrPasswordError,
    UserHasLogined,
    FileNotExist,
    NotOpenFile,
    FileInUse,
    FileExpired,
    NotSameVersion,
    Disconnection,
    ProcessingFile,

    DirNotExist,
    CreateDirError,
    DeleteDirError,
    DeleteFileFailed,
    FileSizeError,
    NotLogined,
    FileAlreadyExist,
    NoConnection,
    EmptyUserInfo,
    WrongProtocolType,
    HostHasStarted,
    HostNotStartYet,
    ArgumentNull,
    SocketClosed,
    DataOutLimit,
    SameVersionAlreadyExist,
}
